package com.testerhome.nativeandroid.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.testerhome.nativeandroid.dao.Favorite;
import com.testerhome.nativeandroid.dao.UserPraiseHistory;

import com.testerhome.nativeandroid.dao.FavoriteDao;
import com.testerhome.nativeandroid.dao.UserPraiseHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favoriteDaoConfig;
    private final DaoConfig userPraiseHistoryDaoConfig;

    private final FavoriteDao favoriteDao;
    private final UserPraiseHistoryDao userPraiseHistoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favoriteDaoConfig = daoConfigMap.get(FavoriteDao.class).clone();
        favoriteDaoConfig.initIdentityScope(type);

        userPraiseHistoryDaoConfig = daoConfigMap.get(UserPraiseHistoryDao.class).clone();
        userPraiseHistoryDaoConfig.initIdentityScope(type);

        favoriteDao = new FavoriteDao(favoriteDaoConfig, this);
        userPraiseHistoryDao = new UserPraiseHistoryDao(userPraiseHistoryDaoConfig, this);

        registerDao(Favorite.class, favoriteDao);
        registerDao(UserPraiseHistory.class, userPraiseHistoryDao);
    }
    
    public void clear() {
        favoriteDaoConfig.getIdentityScope().clear();
        userPraiseHistoryDaoConfig.getIdentityScope().clear();
    }

    public FavoriteDao getFavoriteDao() {
        return favoriteDao;
    }

    public UserPraiseHistoryDao getUserPraiseHistoryDao() {
        return userPraiseHistoryDao;
    }

}
