package com.testerhome.nativeandroid.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.testerhome.nativeandroid.dao.TopicDB;
import com.testerhome.nativeandroid.dao.UserDB;

import com.testerhome.nativeandroid.dao.TopicDBDao;
import com.testerhome.nativeandroid.dao.UserDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig topicDBDaoConfig;
    private final DaoConfig userDBDaoConfig;

    private final TopicDBDao topicDBDao;
    private final UserDBDao userDBDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        topicDBDaoConfig = daoConfigMap.get(TopicDBDao.class).clone();
        topicDBDaoConfig.initIdentityScope(type);

        userDBDaoConfig = daoConfigMap.get(UserDBDao.class).clone();
        userDBDaoConfig.initIdentityScope(type);

        topicDBDao = new TopicDBDao(topicDBDaoConfig, this);
        userDBDao = new UserDBDao(userDBDaoConfig, this);

        registerDao(TopicDB.class, topicDBDao);
        registerDao(UserDB.class, userDBDao);
    }
    
    public void clear() {
        topicDBDaoConfig.getIdentityScope().clear();
        userDBDaoConfig.getIdentityScope().clear();
    }

    public TopicDBDao getTopicDBDao() {
        return topicDBDao;
    }

    public UserDBDao getUserDBDao() {
        return userDBDao;
    }

}
