package com.testerhome.nativeandroid.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "FAVORITE".
 */
public class Favorite implements java.io.Serializable {

    private String id;
    private String title;
    private String created_at;
    private String nodeName;
    private Integer userId;
    private String userLogin;
    private String username;
    private String avatarUrl;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Favorite() {
    }

    public Favorite(String id) {
        this.id = id;
    }

    public Favorite(String id, String title, String created_at, String nodeName, Integer userId, String userLogin, String username, String avatarUrl) {
        this.id = id;
        this.title = title;
        this.created_at = created_at;
        this.nodeName = nodeName;
        this.userId = userId;
        this.userLogin = userLogin;
        this.username = username;
        this.avatarUrl = avatarUrl;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getNodeName() {
        return nodeName;
    }

    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserLogin() {
        return userLogin;
    }

    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
