package com.testerhome.nativeandroid.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TOPIC_DB.
 */
public class TopicDB implements java.io.Serializable {

    private Long id;
    private String title;
    private Boolean is_hot;
    private Boolean is_excellent;
    private Long created_at;
    private Long updated_at;
    private Long replied_at;
    private Integer replies_count;
    private Integer node_id;
    private String node_name;
    private Integer last_reply_user_id;
    private String last_reply_user_login;
    private Integer user_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TopicDB() {
    }

    public TopicDB(Long id) {
        this.id = id;
    }

    public TopicDB(Long id, String title, Boolean is_hot, Boolean is_excellent, Long created_at, Long updated_at, Long replied_at, Integer replies_count, Integer node_id, String node_name, Integer last_reply_user_id, String last_reply_user_login, Integer user_id) {
        this.id = id;
        this.title = title;
        this.is_hot = is_hot;
        this.is_excellent = is_excellent;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.replied_at = replied_at;
        this.replies_count = replies_count;
        this.node_id = node_id;
        this.node_name = node_name;
        this.last_reply_user_id = last_reply_user_id;
        this.last_reply_user_login = last_reply_user_login;
        this.user_id = user_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Boolean getIs_hot() {
        return is_hot;
    }

    public void setIs_hot(Boolean is_hot) {
        this.is_hot = is_hot;
    }

    public Boolean getIs_excellent() {
        return is_excellent;
    }

    public void setIs_excellent(Boolean is_excellent) {
        this.is_excellent = is_excellent;
    }

    public Long getCreated_at() {
        return created_at;
    }

    public void setCreated_at(Long created_at) {
        this.created_at = created_at;
    }

    public Long getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(Long updated_at) {
        this.updated_at = updated_at;
    }

    public Long getReplied_at() {
        return replied_at;
    }

    public void setReplied_at(Long replied_at) {
        this.replied_at = replied_at;
    }

    public Integer getReplies_count() {
        return replies_count;
    }

    public void setReplies_count(Integer replies_count) {
        this.replies_count = replies_count;
    }

    public Integer getNode_id() {
        return node_id;
    }

    public void setNode_id(Integer node_id) {
        this.node_id = node_id;
    }

    public String getNode_name() {
        return node_name;
    }

    public void setNode_name(String node_name) {
        this.node_name = node_name;
    }

    public Integer getLast_reply_user_id() {
        return last_reply_user_id;
    }

    public void setLast_reply_user_id(Integer last_reply_user_id) {
        this.last_reply_user_id = last_reply_user_id;
    }

    public String getLast_reply_user_login() {
        return last_reply_user_login;
    }

    public void setLast_reply_user_login(String last_reply_user_login) {
        this.last_reply_user_login = last_reply_user_login;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
