package com.testerhome.nativeandroid.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table USER_DB.
 */
public class UserDB implements java.io.Serializable {

    private Long user_id;
    private String login;
    private String name;
    private String avatar_url;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserDB() {
    }

    public UserDB(Long user_id) {
        this.user_id = user_id;
    }

    public UserDB(Long user_id, String login, String name, String avatar_url) {
        this.user_id = user_id;
        this.login = login;
        this.name = name;
        this.avatar_url = avatar_url;
    }

    public Long getUser_id() {
        return user_id;
    }

    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAvatar_url() {
        return avatar_url;
    }

    public void setAvatar_url(String avatar_url) {
        this.avatar_url = avatar_url;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
